### ISSUE TITLE
there is a problem with code duplication

### ISSUE THREAD

**Issue by zdf-deep** [Shandilya21/few_shot_research#3]
Hello, I found that there is a problem in the processing of the data in the process of reproduction. Is there something wrong with the dataset?

**Comment by Shandilya21** [comment]
Hello, @zdf-deep Yes In dataset some images are missing, but their description is there in CSV file. we have a total of 44441 images whereas the CSV file has 44447 images_id. you need to delete missing images rows from the CSV file to run the preprocessing script.

**Comment by zdf-deep** [comment]
Thank you for your reply. Could you please send me a copy of the CSV file already processed? I used the smaller sample you mentioned on README





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shandilya21/Few-Shot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月27日(星期一) 下午3:56
收件人:&nbsp;"Shandilya21/Few-Shot"<Few-Shot@noreply.github.com&gt;;
抄送:&nbsp;"自由飞翔"<347900692@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Shandilya21/Few-Shot] there is a problem with code duplication (#3)





 
Hello, @zdf-deep Yes In dataset some images are missing, but their description is there in CSV file. we have a total of 44441 images whereas the CSV file has 44447 images_id. you need to delete missing images rows from the CSV file to run the preprocessing script.

**Comment by Shandilya21** [comment]
Hi, @zdf-deep I think I uploaded with the Preprocessed data, but even if not I know the image_ids which should be removed. 
Sorry, I didn't find the processed CSV in my system. 
```
image_id
1.12347
2.6699
3.16209
4.36399
5.32326
```
Thanks

**Comment by zdf-deep** [comment]
Thank you very much for your help. I have successfully reproduced your code, but the classification accuracy I got is a little bit different from that recorded in your document.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shandilya21/Few-Shot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月27日(星期一) 下午5:07
收件人:&nbsp;"Shandilya21/Few-Shot"<Few-Shot@noreply.github.com&gt;;
抄送:&nbsp;"自由飞翔"<347900692@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Shandilya21/Few-Shot] there is a problem with code duplication (#3)





 
Hi, @zdf-deep I think I uploaded with the Preprocessed data, but even if not I know the image_ids which should be removed.
 Sorry, I didn't find the processed CSV in my system.
 image_id 1.12347 2.6699 3.16209 4.36399 5.32326  
Thanks

**Comment by Shandilya21** [comment]
I have uploaded the results CSV in ```logs/```. you can check the results. A high probability of bit change in classification accuracy that you have reported, as, I tuned some hyper-parameter like ```lr (1e-2, 1e-3, 1e-4)``` etc.  and took an average of 3 random seeds.

**Comment by Shandilya21** [comment]
I am closing this issue, feel free to open this if pop up with a similar question.

**Comment by zdf-deep** [comment]
Can you tell me how to load the weight file (.pth) that you have trained?Thank you very much.
